'use strict';

/**
 * review-pr (IMPL.md §6 step 4 — last guard stage of the `create` pipeline).
 *
 * Audits a diff for drift and side effects after a PR is opened: scope drift,
 * edits to high-fan-in "god-node" files, source changes without matching tests,
 * and changes to security-sensitive files. Pure (takes a changed-file list),
 * zero-dependency, bundle-safe; reuses the impact graph for blast radius.
 */

const fs = require('fs');
const path = require('path');
const { analyzeImpact } = require('../graph/impact');
const { PATTERNS } = require('../security/patterns');
const { findManagedSection, isEntirelyGenerated } = require('../util/managed-section');

const SECURITY_PATTERNS = [
  /(^|\/)\.env(\.|$)/i,
  /(^|\/)(secrets?|credentials?)(\/|\.|$)/i,
  /(^|\/)auth(\/|\.|-)/i,
  /(^|\/)package(-lock)?\.json$/,
  /(^|\/)(yarn\.lock|pnpm-lock\.yaml)$/,
  /(^|\/)\.github\/workflows\//,
  /(^|\/)Dockerfile/i,
  /\.(pem|key|crt|p12)$/i,
];

const SRC_EXTS = new Set(['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.py', '.go', '.rs', '.java', '.rb', '.php']);
const GOD_NODE_THRESHOLD = 15; // transitive dependents → high-fan-in "god node"
const SCOPE_DIR_THRESHOLD = 5; // distinct top-level dirs → scope drift

function isTestFile(p) {
  return /\.(test|spec)\.[jt]sx?$|(^|\/)test_|_test\.(py|go)$|(^|\/)(tests?|__tests__|spec)\//.test(p);
}
function isSource(p) {
  return SRC_EXTS.has(path.extname(p).toLowerCase()) && !isTestFile(p);
}

// SigMap's own outputs (#918). A repo that commits what `sigmap` generates puts
// `.context/*` and the adapter files into every diff next to the real change, and
// they are not part of it: they inflated "files changed", added two top-level
// dirs to the scope-drift count (so 4 real dirs read as 6 > 5 and failed the
// review), and `.context/gain.ndjson` read as `risk: source`.
//
// `.context/` is SigMap's private directory, so it is recognised by path alone.
// The adapter files are only SigMap's when NOTHING human-written is in them:
// CLAUDE.md / AGENTS.md / copilot-instructions.md carry the generated block under
// a marker, below whatever the team wrote. A file with text above the marker is
// a file someone edits, so it stays in the review.
const OWN_DIR = /^\.context\//;
const OWN_JSON = '.github/copilot-instructions.cache.json';
// `llm.txt` is deliberately absent: it is a template the team fills in by hand.
const OWN_CONTEXT_FILES = new Set([
  '.github/copilot-instructions.md', 'CLAUDE.md', 'AGENTS.md', '.cursorrules', '.windsurfrules',
  '.github/openai-context.md', '.github/gemini-context.md', 'llms.txt', 'llm-full.txt',
]);
// First lines of the outputs SigMap overwrites whole, which managed-section.js
// does not know: cursor / windsurf, openai, and the two text indexes
// (`# SigMap Context Index`, `# <name> — SigMap Context`).
const WHOLE_FILE_OPENERS = [
  /^# Code signatures — generated by SigMap\b/,
  /^You are a coding assistant with full knowledge of this codebase\./,
  /^# (?:.* — )?SigMap Context(?: Index)?\s*$/,
];
// The two blocks SigMap itself writes ABOVE the managed marker: the claude
// adapter's `## Bash allowlist` (packages/adapters/claude.js) and the skills
// block `sigmap skills` injects (src/skills/skills.js). The adapter sweep in
// review-pr.test.js fails if either stops matching.
const SKILLS_BLOCK = /<!-- sigmap-skills:start -->[\s\S]*?<!-- sigmap-skills:end -->/g;
const ALLOWLIST_BLOCK = /## Bash allowlist\s*\n\s*<!-- sigmap-bash-allowlist -->[\s\S]*?```json[\s\S]*?```[ \t]*\n?(?:\s*Add the `permissions\.allow`[^\n]*\n?)?/;

/** Whether a generated file's text is SigMap's from the first line (nothing human above the marker). */
function _entirelyGenerated(text) {
  if (isEntirelyGenerated(text)) return true;
  const first = text.replace(/^(?:[ \t]*\r?\n)+/, '').split('\n', 1)[0].replace(/\r$/, '');
  if (WHOLE_FILE_OPENERS.some((re) => re.test(first))) return true;
  const section = findManagedSection(text);
  if (!section) return false;
  return text.slice(0, section.index).replace(SKILLS_BLOCK, '').replace(ALLOWLIST_BLOCK, '').trim() === '';
}

/**
 * Whether a changed path is a file SigMap wrote and no one edits.
 * @param {string} rel repo-relative path
 * @param {(rel:string)=>string} read returns the file's text; may throw
 * @returns {boolean}
 */
function isSigmapOutput(rel, read) {
  const p = String(rel).replace(/\\/g, '/');
  if (OWN_DIR.test(p) || p === OWN_JSON) return true;
  if (!OWN_CONTEXT_FILES.has(p)) return false;
  try {
    const text = read(p);
    return typeof text === 'string' && _entirelyGenerated(text);
  } catch (_) {
    return false; // deleted or unreadable: cannot show it is all generated, so it counts
  }
}

/**
 * Audit a changed-file list.
 * @param {Array<{path:string,status:string}>|string[]} changedFiles
 * @param {string} cwd
 * @param {object} [opts]
 * @param {number} [opts.godNodeThreshold=15]
 * @param {number} [opts.scopeThreshold=5]
 * @returns {{ findings: object[], blast: object[], methodBlast: object|null, ignored: string[], summary: object }}
 *   `ignored` lists the SigMap-generated outputs left out of the review (#918)
 */
function reviewPr(changedFiles, cwd, opts = {}) {
  const godThreshold = opts.godNodeThreshold != null ? opts.godNodeThreshold : GOD_NODE_THRESHOLD;
  const scopeThreshold = opts.scopeThreshold != null ? opts.scopeThreshold : SCOPE_DIR_THRESHOLD;
  const readFile = opts.readFile || ((p) => fs.readFileSync(path.resolve(cwd, p), 'utf8'));
  const all = (changedFiles || []).map((f) => (typeof f === 'string' ? { path: f, status: 'M' } : f));
  const ignored = all.filter((f) => isSigmapOutput(f.path, readFile)).map((f) => f.path);
  const files = ignored.length ? all.filter((f) => !ignored.includes(f.path)) : all;

  const findings = [];
  const paths = files.map((f) => f.path);
  const live = files.filter((f) => f.status !== 'D');
  const srcChanged = live.filter((f) => isSource(f.path)).map((f) => f.path);
  const testChanged = paths.filter(isTestFile);

  // 1. Missing tests: a changed source file with no matching changed test file.
  for (const s of srcChanged) {
    const stem = path.basename(s).replace(/\.[^.]+$/, '');
    const covered = testChanged.some((t) => path.basename(t).includes(stem));
    if (!covered) findings.push({ type: 'missing-tests', file: s, severity: 'warn' });
  }

  // 2a. Sensitive-path heuristic — flags files whose PATH looks security-relevant
  // (.env, auth/, lockfiles, workflows, key material). This is a path heuristic,
  // NOT a content scan: it flags touching the path regardless of what changed,
  // and cannot see a secret hidden in an innocently-named file. `basis` records
  // that honestly so consumers don't mistake it for a content check.
  for (const f of live) {
    if (SECURITY_PATTERNS.some((re) => re.test(f.path))) {
      findings.push({ type: 'security-file', file: f.path, severity: 'warn', basis: 'path-heuristic' });
    }
  }

  // 2b. Real secret scan — read each changed file's CONTENT and match known
  // secret patterns. This is the actual security check (content, not filename):
  // it catches a hardcoded key in a file the path heuristic would never flag.
  for (const f of live) {
    let content;
    try { content = readFile(f.path); } catch (_) { continue; } // absent/unreadable → skip
    if (typeof content !== 'string' || content.length > 2_000_000) continue; // skip huge/binary
    for (const pat of PATTERNS) {
      if (pat.regex.test(content)) {
        findings.push({ type: 'secret-detected', file: f.path, secret: pat.name, severity: 'high', basis: 'content-scan' });
        break; // one hit is enough to flag the file
      }
    }
  }

  // 3. God-node edits (high blast radius).
  const blast = [];
  if (srcChanged.length) {
    let impacts = [];
    try { impacts = analyzeImpact(srcChanged, cwd, {}); } catch (_) { impacts = []; }
    for (const { file, impact } of impacts) {
      blast.push({ file, totalImpact: impact.totalImpact });
      if (impact.totalImpact > godThreshold) {
        findings.push({ type: 'god-node', file, count: impact.totalImpact, severity: 'warn' });
      }
    }
    blast.sort((a, b) => b.totalImpact - a.totalImpact);
  }

  // 3b. Method-level blast radius (GR2) — how many FUNCTIONS transitively call
  // into the change, scored deterministically. Graph optional, like 3.
  let methodBlast = null;
  if (srcChanged.length) {
    try {
      const { methodBlastRadius } = require('../graph/blast-radius');
      const mb = methodBlastRadius(srcChanged, cwd, opts.methodBlastOpts || {});
      if (mb.available) {
        methodBlast = mb;
        for (const f of mb.files) {
          if (f.tier === 'high' || f.tier === 'critical') {
            findings.push({
              type: 'method-blast', file: f.file, severity: 'warn',
              functions: f.directCallers + f.transitiveCallers, score: f.score, tier: f.tier,
            });
          }
        }
      }
    } catch (_) { /* call graph optional */ }
  }

  // 4. Scope drift: distinct top-level directories touched.
  const dirs = [...new Set(paths.map((p) => (p.includes('/') ? p.split('/')[0] : '.')))];
  if (dirs.length > scopeThreshold) {
    findings.push({ type: 'scope-drift', dirs, count: dirs.length, threshold: scopeThreshold, severity: 'warn' });
  }

  const byType = findings.reduce((a, f) => { a[f.type] = (a[f.type] || 0) + 1; return a; }, {});
  return {
    findings,
    blast,
    methodBlast,
    ignored,
    summary: {
      filesChanged: files.length,
      generatedIgnored: ignored.length,
      sourceChanged: srcChanged.length,
      testsChanged: testChanged.length,
      findings: findings.length,
      byType,
      ok: findings.length === 0,
    },
  };
}

module.exports = { reviewPr, isSigmapOutput, SECURITY_PATTERNS, GOD_NODE_THRESHOLD, SCOPE_DIR_THRESHOLD };
