'use strict';

/**
 * managed-section.js — the one place that finds SigMap's generated block inside
 * a human-owned context file (CLAUDE.md, AGENTS.md, GEMINI.md,
 * copilot-instructions.md) and replaces it (#873).
 *
 * The contract every writer states is "never overwrite human-written content".
 * It was enforced by `existing.indexOf('## Auto-generated signatures')` — the
 * FIRST occurrence anywhere — followed by discarding everything after it. A file
 * that merely MENTIONED the marker (in prose, in a code block, in a doc about
 * SigMap itself) therefore lost every human line after the mention, on the next
 * run, with no warning and no way back when the file is untracked. The same
 * substring test also decided that a file was "legacy generated" and replaced it
 * whole. Four adapters, the CLI core writer, the skills injector and two readers
 * each carried their own copy of it.
 *
 * What counts as the managed section now:
 *
 *   stamped   the heading immediately followed by the stamp comment the writers
 *             emit (`<!-- Updated by gen-context.js -->`). Machine-written text
 *             that prose does not produce; the LAST one wins, because the
 *             generated block is always appended after every human line.
 *   bare      a heading on its own line with no stamp. Found, so readers and
 *             injectors can use it, but REPLACED only when what follows looks
 *             SigMap-generated — a human section that happens to share the title
 *             is appended after, with a warning, never cut.
 *
 * Neither is taken from inside a fenced code block, with one exception: a
 * stamped heading inside a fence still counts when a generated block follows it
 * (see findManagedSection). An unterminated fence is not a fence: otherwise one
 * stray ``` hides the real marker, and the writer would append a fresh block on
 * every run.
 *
 * Zero dependencies. Pure string functions — no fs — so the bundled CLI core,
 * the adapters and every src/ module share them.
 */

const HEADING = '## Auto-generated signatures';
const STAMP = '<!-- Updated by gen-context.js -->';

/** What a writer appends when the file has no managed section yet. */
const MARKER = `\n\n${HEADING}\n${STAMP}\n`;

// Heading + stamp as two consecutive lines. NOT anchored to the start of a line:
// files already damaged by the old slice have the heading glued to the end of
// the prose line that quoted it, and recognising that shape lets the next run
// repair them in place instead of appending a second block.
const STAMPED_RE = new RegExp(`${HEADING}[ \\t]*\\r?\\n${STAMP.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g');
const BARE_RE = new RegExp(`^${HEADING}[ \\t]*\\r?$`, 'gm');

/**
 * How the first non-blank line of a block SigMap generated begins. One entry per
 * adapter format() plus the legacy forms; test/integration/managed-section.test.js
 * asserts every adapter still writes a block this recognises.
 */
const GENERATED_OPENERS = [
  /^<!-- Generated by SigMap\b/,                                  // claude, copilot
  /^#{1,2} Code [Ss]ignatures\s*$/,                                // codex, CLI core, legacy
  /^You are a coding assistant with complete knowledge of this codebase\./, // gemini
];

/** Offsets [start, end) of every balanced fenced code block in `text`. */
function fencedRanges(text) {
  const lines = text.split('\n');
  const offsets = [];
  let off = 0;
  for (const l of lines) { offsets.push(off); off += l.length + 1; }

  const ignored = new Set(); // line indexes of openers that never closed
  for (;;) {
    const ranges = [];
    let open = null; // { line, char, len }
    for (let i = 0; i < lines.length; i++) {
      if (ignored.has(i)) continue;
      const m = lines[i].match(/^ {0,3}(`{3,}|~{3,})/);
      if (!m) continue;
      const char = m[1][0];
      if (open === null) {
        open = { line: i, char, len: m[1].length };
      } else if (char === open.char && m[1].length >= open.len
        && /^[ \t]*\r?$/.test(lines[i].slice(lines[i].indexOf(m[1]) + m[1].length))) {
        ranges.push([offsets[open.line], offsets[i] + lines[i].length]);
        open = null;
      }
    }
    if (open === null) return ranges;
    ignored.add(open.line); // an unterminated fence is not a fence — rescan without it
  }
}

const inside = (ranges, idx) => ranges.some(([a, b]) => idx >= a && idx < b);

/** Text after the heading (and its stamp line, when present), without leading blank lines. */
function afterHeading(text, index) {
  const nl = text.indexOf('\n', index);
  let rest = nl === -1 ? '' : text.slice(nl + 1);
  if (rest.startsWith(STAMP)) {
    const n2 = rest.indexOf('\n');
    rest = n2 === -1 ? '' : rest.slice(n2 + 1);
  }
  return rest.replace(/^(?:[ \t]*\r?\n)+/, '');
}

/** Whether the first non-blank line after a heading opens a SigMap-generated block. */
function looksGenerated(text, index) {
  const rest = afterHeading(text, index);
  if (rest === '') return true; // nothing after it — nothing to lose
  const first = rest.split('\n', 1)[0].replace(/\r$/, '');
  return GENERATED_OPENERS.some((re) => re.test(first));
}

/**
 * Locate the managed section.
 * @param {string} text
 * @returns {{ index: number, stamped: boolean }|null} `index` is where the heading starts
 */
function findManagedSection(text) {
  const src = String(text || '');
  if (!src.includes(HEADING)) return null;
  const fences = fencedRanges(src);

  // A stamped heading is trusted outside a fence. Inside one it must also be
  // followed by a generated block: a file the old bug truncated mid-fence has
  // its real heading "inside" an unclosed fence whose pairing the generated
  // block's own fences then shift, while a fence that merely QUOTES the marker
  // has no generated block after it.
  let found = null;
  STAMPED_RE.lastIndex = 0;
  for (let m; (m = STAMPED_RE.exec(src)) !== null;) {
    if (!inside(fences, m.index) || looksGenerated(src, m.index)) found = { index: m.index, stamped: true };
  }
  if (found) return found;

  BARE_RE.lastIndex = 0;
  for (let m; (m = BARE_RE.exec(src)) !== null;) {
    if (!inside(fences, m.index)) found = { index: m.index, stamped: false };
  }
  return found;
}

/**
 * Start of the managed section's line — where a block injected "above the
 * marker" must go, so it never lands in the middle of a prose line.
 * @returns {number} -1 when there is no managed section
 */
function managedSectionLineStart(text) {
  const m = findManagedSection(text);
  if (!m) return -1;
  return String(text).lastIndexOf('\n', m.index - 1) + 1;
}

/** Whether the whole file is a generated block with no marker (the pre-marker format). */
function isEntirelyGenerated(text) {
  const first = String(text || '').replace(/^(?:[ \t]*\r?\n)+/, '').split('\n', 1)[0].replace(/\r$/, '');
  return first !== '' && GENERATED_OPENERS.some((re) => re.test(first));
}

/**
 * Put `block` (the adapter's formatted output) into `existing` under the marker.
 *
 *   replaced   a managed section was found; everything before it is untouched
 *   appended   none was found (or a bare heading did not look generated);
 *              `existing` is untouched and the section follows it
 *   legacy     `opts.legacy` and the whole file was a pre-marker generated block
 *   created    `existing` was empty
 *
 * Never returns less human content than it was given, except by replacing a
 * section that is positively a SigMap block.
 *
 * @param {string} existing
 * @param {string} block
 * @param {{ legacy?: boolean }} [opts]  legacy: replace a file that is ENTIRELY a
 *        pre-marker generated block (copilot, gemini, codex did; claude never did)
 * @returns {{ content: string, action: 'replaced'|'appended'|'legacy'|'created', warning: string|null }}
 */
function replaceManagedSection(existing, block, opts = {}) {
  const src = String(existing || '');
  const section = findManagedSection(src);
  // A stamped heading is machine-written and is replaced. A bare one is a line
  // somebody typed, so it is replaced only when what follows it is positively a
  // SigMap block — otherwise the file asked to be treated as managed and was not,
  // and replacing would discard human lines. That is the one case worth saying out loud.
  let warning = null;
  if (section && (section.stamped || looksGenerated(src, section.index))) {
    return {
      content: src.slice(0, section.index) + MARKER.trimStart() + block,
      action: 'replaced',
      warning: null,
    };
  }
  if (section) {
    const line = src.slice(0, section.index).split('\n').length;
    warning = `found "${HEADING}" at line ${line} but what follows it is not a SigMap-generated block — appended a new section instead of replacing it`;
  } else if (src === '') {
    return { content: MARKER + block, action: 'created', warning: null };
  } else if (opts.legacy && isEntirelyGenerated(src)) {
    return { content: MARKER.trimStart() + block, action: 'legacy', warning: null };
  }
  return { content: src + MARKER + block, action: 'appended', warning };
}

module.exports = {
  HEADING, STAMP, MARKER, GENERATED_OPENERS,
  findManagedSection, managedSectionLineStart, isEntirelyGenerated, looksGenerated, replaceManagedSection,
};
