'use strict';

/**
 * Model routing hint definitions for SigMap.
 *
 * Maps complexity tiers to the task types that belong to each. The model names
 * and prices a tier prints are NOT defined here: they come from the dated model
 * profile (src/config/models.js), the same table `gain --model` prices from, so
 * a name advised here is always one the pricing accepts (#778).
 *
 * These are embedded in the generated context file when `routing: true`
 * so that AI agents and developers know which model tier to invoke.
 */

const { resolveProfile, tierModels, tierPriceRange, asOfLabel, TIER_ORDER } = require('../config/models');

const TIER_TASKS = {
  fast: {
    label: 'Fast (low-cost)',
    tasks: [
      'Autocomplete and inline suggestions',
      'Edit config or markup files',
      'Fix typos and rename symbols',
      'Format, lint, and trivial style changes',
      'Explain a short utility function',
      'Generate simple shell scripts or Dockerfiles',
    ],
  },

  balanced: {
    label: 'Balanced (mid-tier)',
    tasks: [
      'Write unit or integration tests',
      'Implement a well-scoped feature function',
      'Debug a runtime error with stack trace',
      'Refactor a module (< 200 lines)',
      'Generate a PR description',
      'Explain a multi-function module',
    ],
  },

  powerful: {
    label: 'Powerful (high-cost)',
    tasks: [
      'Cross-cutting architecture decisions',
      'Multi-file refactor spanning 5+ files',
      'Security audit (OWASP Top 10)',
      'Complex debugging across async boundaries',
      'Migration plan for a library/framework upgrade',
      'Designing a new module from requirements',
    ],
  },
};

/**
 * One tier as advice: its tasks plus the models and input-price span the
 * profile in force gives it.
 *
 * @param {string} tier - 'fast' | 'balanced' | 'powerful'
 * @param {object} [profile] - from resolveProfile(config); the shipped profile when omitted
 * @returns {{ label: string, tasks: string[], models: string[], examples: string, costHint: string }}
 */
function tierInfo(tier, profile) {
  const p = profile || resolveProfile();
  const models = tierModels(p, tier);
  const range = tierPriceRange(p, tier);
  const costHint = !range
    ? 'no priced model in this tier'
    : (range.min === range.max ? `$${range.min}` : `$${range.min}–$${range.max}`) + ' / MTok input';
  return {
    label: TIER_TASKS[tier].label,
    tasks: TIER_TASKS[tier].tasks,
    models,
    examples: models.length ? models.join(', ') : (p.rosterDeclared ? '(none in your roster)' : '(none)'),
    costHint,
  };
}

/** The tiers under the shipped profile, for callers with no config in hand. */
const TIERS = {};
for (const tier of TIER_ORDER) TIERS[tier] = tierInfo(tier);

/**
 * Format the routing section as markdown to append to the context file.
 *
 * @param {{ fast: string[], balanced: string[], powerful: string[] }} groups
 *   Relative file paths grouped by tier (from classifier.classifyAll).
 * @param {object} [profile] - from resolveProfile(config); the shipped profile when omitted
 * @returns {string} Markdown block to embed in the context output.
 */
function formatRoutingSection(groups, profile) {
  const p = profile || resolveProfile();
  const lines = [
    '',
    '---',
    '',
    '## Model routing hints',
    '<!-- Generated by SigMap routing module — update gen-context.config.json to disable -->',
    '',
    'Select the model tier based on the task complexity and the files involved.',
    `Model names and prices: ${asOfLabel(p)} — a static table, not a live lookup.`,
    '',
  ];

  for (const tier of TIER_ORDER) {
    const info = tierInfo(tier, p);
    const files = groups[tier] || [];
    lines.push(`### ${info.label}`);
    lines.push(`**Examples:** ${info.examples}  `);
    lines.push(`**Cost:** ${info.costHint}`);
    lines.push('');
    lines.push('**Use for tasks like:**');
    for (const task of info.tasks) lines.push(`- ${task}`);
    lines.push('');
    if (files.length > 0) {
      lines.push('**Files in this tier:**');
      for (const f of files.slice(0, 15)) lines.push(`- \`${f}\``);
      if (files.length > 15) lines.push(`- … and ${files.length - 15} more`);
    } else {
      lines.push('**Files in this tier:** _(none detected)_');
    }
    lines.push('');
  }

  lines.push('> **Tip:** Run `node gen-context.js --routing` to regenerate routing hints.');
  lines.push('> See `docs/MODEL_ROUTING.md` for full routing guide and cost optimisation tips.');

  return lines.join('\n');
}

module.exports = { TIERS, tierInfo, formatRoutingSection };
