'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const assert = require('assert');
const { execSync } = require('child_process');

const GEN_CONTEXT = path.resolve(__dirname, '../../gen-context.js');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  PASS  ${name}`);
    passed++;
  } catch (err) {
    console.log(`  FAIL  ${name}: ${err.message}`);
    failed++;
  }
}

/**
 * Send one or more newline-separated JSON-RPC messages to the MCP server
 * via stdin, collect stdout, return array of parsed response objects.
 */
function mcpCall(messages, cwd) {
  const input = (Array.isArray(messages) ? messages : [messages])
    .map((m) => JSON.stringify(m))
    .join('\n') + '\n';

  const stdout = execSync(`node "${GEN_CONTEXT}" --mcp`, {
    input,
    cwd,
    encoding: 'utf8',
    timeout: 10000,
  });

  return stdout
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l));
}

function withTempProject(fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cf-mcp-'));
  try {
    fn(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function seedContextFile(dir) {
  const ghDir = path.join(dir, '.github');
  fs.mkdirSync(ghDir, { recursive: true });
  fs.writeFileSync(
    path.join(ghDir, 'copilot-instructions.md'),
    [
      '<!-- Generated by ContextForge -->',
      '# Code signatures',
      '',
      '## src',
      '',
      '### src/auth/login.js',
      '```',
      'function login(user, pass)',
      'function logout(session)',
      '```',
      '',
      '### src/api/routes.js',
      '```',
      'function getUser(req, res)',
      'function createUser(req, res)',
      '```',
      '',
    ].join('\n')
  );
}

// ─────────────────────────────────────────────────────────────
// Gate 1: initialize handshake
// ─────────────────────────────────────────────────────────────
test('initialize returns serverInfo', () => {
  withTempProject((dir) => {
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'initialize', id: 1, params: { protocolVersion: '2024-11-05', capabilities: {} } },
      dir
    );
    assert.strictEqual(res.jsonrpc, '2.0');
    assert.strictEqual(res.id, 1);
    assert.ok(res.result, 'Should have result');
    assert.strictEqual(res.result.serverInfo.name, 'context-forge');
    assert.ok(res.result.protocolVersion, 'Should have protocolVersion');
    assert.ok(res.result.capabilities, 'Should have capabilities');
  });
});

// ─────────────────────────────────────────────────────────────
// Gate 2: tools/list returns 3 tools
// ─────────────────────────────────────────────────────────────
test('tools/list returns exactly 3 tools', () => {
  withTempProject((dir) => {
    const [res] = mcpCall({ jsonrpc: '2.0', method: 'tools/list', id: 2 }, dir);
    assert.ok(res.result, 'Should have result');
    assert.ok(Array.isArray(res.result.tools), 'tools should be array');
    assert.strictEqual(res.result.tools.length, 3);
    const names = res.result.tools.map((t) => t.name);
    assert.ok(names.includes('read_context'), 'Should have read_context');
    assert.ok(names.includes('search_signatures'), 'Should have search_signatures');
    assert.ok(names.includes('get_map'), 'Should have get_map');
  });
});

// ─────────────────────────────────────────────────────────────
// Gate 3: read_context returns signatures
// ─────────────────────────────────────────────────────────────
test('read_context returns full context file content', () => {
  withTempProject((dir) => {
    seedContextFile(dir);
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 3, params: { name: 'read_context', arguments: {} } },
      dir
    );
    assert.ok(res.result, 'Should have result');
    const text = res.result.content[0].text;
    assert.ok(text.includes('login'), 'Should include login signature');
    assert.ok(text.includes('getUser'), 'Should include getUser signature');
  });
});

// ─────────────────────────────────────────────────────────────
// Gate 4: read_context with module filter
// ─────────────────────────────────────────────────────────────
test('read_context with module filters to matching files', () => {
  withTempProject((dir) => {
    seedContextFile(dir);
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 4, params: { name: 'read_context', arguments: { module: 'src/auth' } } },
      dir
    );
    const text = res.result.content[0].text;
    assert.ok(text.includes('login'), 'Should include auth signatures');
    assert.ok(!text.includes('getUser'), 'Should NOT include api signatures');
  });
});

// ─────────────────────────────────────────────────────────────
// search_signatures
// ─────────────────────────────────────────────────────────────
test('search_signatures returns matching lines', () => {
  withTempProject((dir) => {
    seedContextFile(dir);
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 5, params: { name: 'search_signatures', arguments: { query: 'user' } } },
      dir
    );
    const text = res.result.content[0].text;
    assert.ok(text.includes('createUser') || text.includes('getUser'), 'Should find user-related signatures');
  });
});

test('search_signatures returns no-match message when nothing found', () => {
  withTempProject((dir) => {
    seedContextFile(dir);
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 6, params: { name: 'search_signatures', arguments: { query: 'xyzzy_nonexistent_12345' } } },
      dir
    );
    const text = res.result.content[0].text;
    assert.ok(text.includes('No signatures found'), 'Should return no-match message');
  });
});

// ─────────────────────────────────────────────────────────────
// get_map with missing PROJECT_MAP.md
// ─────────────────────────────────────────────────────────────
test('get_map returns error when PROJECT_MAP.md missing', () => {
  withTempProject((dir) => {
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 7, params: { name: 'get_map', arguments: { type: 'imports' } } },
      dir
    );
    const text = res.result.content[0].text;
    assert.ok(text.includes('PROJECT_MAP.md not found'), 'Should report missing file');
  });
});

// ─────────────────────────────────────────────────────────────
// Unknown tool → error response
// ─────────────────────────────────────────────────────────────
test('unknown tool returns error response', () => {
  withTempProject((dir) => {
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 8, params: { name: 'nonexistent_tool', arguments: {} } },
      dir
    );
    assert.ok(res.error, 'Should return error object');
    assert.ok(res.error.message.includes('Unknown tool'), 'Error should mention Unknown tool');
  });
});

// ─────────────────────────────────────────────────────────────
// Unknown method → error response
// ─────────────────────────────────────────────────────────────
test('unknown method returns error response', () => {
  withTempProject((dir) => {
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'resources/list', id: 9 },
      dir
    );
    assert.ok(res.error, 'Should return error object');
    assert.strictEqual(res.error.code, -32601);
  });
});

// ─────────────────────────────────────────────────────────────
// Multiple messages in one session
// ─────────────────────────────────────────────────────────────
test('multiple messages in a single session all get responses', () => {
  withTempProject((dir) => {
    seedContextFile(dir);
    const responses = mcpCall(
      [
        { jsonrpc: '2.0', method: 'initialize', id: 1, params: { protocolVersion: '2024-11-05', capabilities: {} } },
        { jsonrpc: '2.0', method: 'tools/list', id: 2 },
        { jsonrpc: '2.0', method: 'tools/call', id: 3, params: { name: 'read_context', arguments: {} } },
      ],
      dir
    );
    assert.strictEqual(responses.length, 3, 'Should get 3 responses');
    assert.strictEqual(responses[0].id, 1);
    assert.strictEqual(responses[1].id, 2);
    assert.strictEqual(responses[2].id, 3);
  });
});

// ─────────────────────────────────────────────────────────────
// read_context when no context file exists
// ─────────────────────────────────────────────────────────────
test('read_context returns helpful message when no context file', () => {
  withTempProject((dir) => {
    // No seedContextFile — no .github/copilot-instructions.md
    const [res] = mcpCall(
      { jsonrpc: '2.0', method: 'tools/call', id: 10, params: { name: 'read_context', arguments: {} } },
      dir
    );
    const text = res.result.content[0].text;
    assert.ok(text.includes('gen-context.js'), 'Should suggest running gen-context.js');
  });
});

console.log('');
console.log(`mcp-server: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
