'use strict';

/**
 * Integration tests for `sigmap review-pr` (Gap 2, step 4).
 *   reviewPr: missing-tests / security-file / god-node / scope-drift · CLI (git diff)
 */

const assert = require('assert');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { spawnSync, execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '../..');
const SCRIPT = path.join(ROOT, 'gen-context.js');
const { reviewPr, isSigmapOutput } = require(path.join(ROOT, 'src/review/review-pr'));
const { buildPrEvidence, formatPrEvidenceMarkdown } = require(path.join(ROOT, 'src/review/pr-evidence'));

let passed = 0, failed = 0;
function test(name, fn) {
  try { fn(); console.log(`  PASS  ${name}`); passed++; }
  catch (err) { console.error(`  FAIL  ${name}`); console.error(`        ${err.message}`); failed++; }
}

// ── reviewPr (pure) ─────────────────────────────────────────────────────────
test('missing-tests: source changed without matching test', () => {
  const r = reviewPr([{ path: 'src/foo.js', status: 'M' }], process.cwd());
  assert.ok(r.findings.some((f) => f.type === 'missing-tests' && f.file === 'src/foo.js'));
});
test('no missing-tests when a matching test changed', () => {
  const r = reviewPr([
    { path: 'src/foo.js', status: 'M' },
    { path: 'test/foo.test.js', status: 'M' },
  ], process.cwd());
  assert.ok(!r.findings.some((f) => f.type === 'missing-tests'));
});
test('security-file: flags sensitive paths (path heuristic, basis recorded)', () => {
  const r = reviewPr([
    { path: '.env', status: 'M' },
    { path: '.github/workflows/ci.yml', status: 'M' },
    { path: 'package.json', status: 'M' },
    { path: 'src/auth/login.js', status: 'M' },
  ], process.cwd(), { readFile: () => '' });
  const secFindings = r.findings.filter((f) => f.type === 'security-file');
  const sec = secFindings.map((f) => f.file);
  assert.ok(sec.includes('.env'));
  assert.ok(sec.includes('.github/workflows/ci.yml'));
  assert.ok(sec.includes('package.json'));
  // honest labeling: the finding declares it is a path heuristic, not a scan
  assert.ok(secFindings.every((f) => f.basis === 'path-heuristic'), 'security-file must record basis: path-heuristic');
});

test('secret-detected: content scan flags a hardcoded key in an innocent file', () => {
  const r = reviewPr([{ path: 'src/utils.js', status: 'M' }], process.cwd(), {
    readFile: () => 'const k = "AKIAABCDEFGHIJKLMNOP";\n', // AWS-access-key shaped
  });
  const hits = r.findings.filter((f) => f.type === 'secret-detected');
  assert.strictEqual(hits.length, 1, `expected one secret finding, got ${JSON.stringify(r.findings)}`);
  assert.strictEqual(hits[0].secret, 'AWS Access Key');
  assert.strictEqual(hits[0].basis, 'content-scan');
  assert.strictEqual(r.summary.ok, false, 'a detected secret must fail the review');
});

test('secret-detected: clean content produces no secret finding', () => {
  const r = reviewPr([{ path: 'src/utils.js', status: 'M' }], process.cwd(), {
    readFile: () => 'function add(a, b) { return a + b; }\n',
  });
  assert.ok(!r.findings.some((f) => f.type === 'secret-detected'));
});
test('deletions are ignored for security + source checks', () => {
  const r = reviewPr([{ path: '.env', status: 'D' }, { path: 'src/foo.js', status: 'D' }], process.cwd());
  assert.ok(!r.findings.some((f) => f.type === 'security-file'));
  assert.ok(!r.findings.some((f) => f.type === 'missing-tests'));
});
test('scope-drift: too many top-level dirs', () => {
  const files = ['a', 'b', 'c', 'd', 'e', 'f'].map((d) => ({ path: `${d}/x.js`, status: 'M' }));
  const r = reviewPr(files, process.cwd(), { scopeThreshold: 5 });
  assert.ok(r.findings.some((f) => f.type === 'scope-drift' && f.count === 6));
});
test('summary: byType + ok=false when findings present', () => {
  const r = reviewPr([{ path: '.env', status: 'M' }], process.cwd());
  assert.strictEqual(r.summary.ok, false);
  assert.strictEqual(r.summary.byType['security-file'], 1);
});
test('summary: ok=true when clean', () => {
  const r = reviewPr([
    { path: 'src/foo.js', status: 'M' },
    { path: 'src/foo.test.js', status: 'M' },
  ], process.cwd());
  assert.strictEqual(r.summary.ok, true);
  assert.strictEqual(r.findings.length, 0);
});

// ── SigMap's own outputs are not part of the change (#918) ─────────────────
const GENERATED = [
  '<!-- Generated by SigMap gen-context.js v8.70.0 -->',
  '<!-- DO NOT EDIT below the marker line — run gen-context.js to regenerate -->',
  '',
  '# Code signatures',
  '',
].join('\n');
const OWN_OUTPUTS = [
  { path: '.context/gain.ndjson', status: 'M' },
  { path: '.context/sig-index.json', status: 'M' },
  { path: '.github/copilot-instructions.md', status: 'M' },
];
const readOwn = (p) => (p === '.github/copilot-instructions.md' ? GENERATED : 'x\n');
const REAL = [
  { path: 'src/a.js', status: 'M' }, { path: 'lib/b.js', status: 'M' }, { path: 'app/c.js', status: 'M' },
  { path: 'test/a.test.js', status: 'M' }, { path: 'test/b.test.js', status: 'M' }, { path: 'test/c.test.js', status: 'M' },
];

test('own outputs: the verdict, counts and scope do not change when they sit in the diff', () => {
  const opts = { readFile: readOwn, scopeThreshold: 5 };
  const without = reviewPr(REAL, process.cwd(), opts);
  const withOwn = reviewPr([...REAL, ...OWN_OUTPUTS], process.cwd(), opts);
  assert.deepStrictEqual(withOwn.findings, without.findings);
  assert.strictEqual(withOwn.summary.filesChanged, without.summary.filesChanged);
  assert.strictEqual(withOwn.summary.sourceChanged, without.summary.sourceChanged);
  assert.strictEqual(withOwn.summary.ok, without.summary.ok);
  assert.ok(!withOwn.findings.some((f) => f.type === 'scope-drift'),
    '4 real dirs + .context + .github must not read as 6 > 5');
});

test('own outputs: they are reported, not silently dropped', () => {
  const r = reviewPr([...REAL, ...OWN_OUTPUTS], process.cwd(), { readFile: readOwn });
  assert.deepStrictEqual(r.ignored.sort(), OWN_OUTPUTS.map((f) => f.path).sort());
  assert.strictEqual(r.summary.generatedIgnored, OWN_OUTPUTS.length);
  assert.strictEqual(reviewPr(REAL, process.cwd(), { readFile: readOwn }).summary.generatedIgnored, 0);
});

test('own outputs: a diff made only of them reviews clean, with nothing to flag', () => {
  const r = reviewPr(OWN_OUTPUTS, process.cwd(), { readFile: readOwn });
  assert.strictEqual(r.summary.filesChanged, 0);
  assert.strictEqual(r.summary.ok, true);
});

test('own outputs: a CLAUDE.md with human text above the marker is still reviewed', () => {
  const human = '# My project\n\nAlways run the tests first.\n\n## Auto-generated signatures\n<!-- Updated by gen-context.js -->\n' + GENERATED;
  const r = reviewPr([{ path: 'CLAUDE.md', status: 'M' }], process.cwd(), { readFile: () => human });
  assert.strictEqual(r.summary.filesChanged, 1, 'a file a human edits is part of the change');
  assert.deepStrictEqual(r.ignored, []);
});

test('own outputs: a CLAUDE.md that is generated from its first line is not reviewed', () => {
  const created = '\n\n## Auto-generated signatures\n<!-- Updated by gen-context.js -->\n' + GENERATED;
  assert.strictEqual(isSigmapOutput('CLAUDE.md', () => created), true);
  assert.strictEqual(isSigmapOutput('AGENTS.md', () => GENERATED), true);
});

test('own outputs: a deleted or unreadable adapter file counts (it cannot be shown to be all generated)', () => {
  const gone = () => { throw new Error('ENOENT'); };
  assert.strictEqual(isSigmapOutput('CLAUDE.md', gone), false);
  const r = reviewPr([{ path: 'CLAUDE.md', status: 'D' }], process.cwd(), { readFile: gone });
  assert.strictEqual(r.summary.filesChanged, 1);
});

test('own outputs: ordinary files and look-alikes are never ignored', () => {
  const read = () => GENERATED; // even generated-looking text does not matter off the list
  for (const p of ['src/context.js', 'docs/CLAUDE.md', '.github/workflows/ci.yml', 'llm.txt', 'my.context/x.json', 'README.md']) {
    assert.strictEqual(isSigmapOutput(p, read), false, p);
  }
  assert.strictEqual(isSigmapOutput('.context\\gain.ndjson', read), true, 'windows separators');
});

test('own outputs: every shipped adapter writes a file the review recognises', () => {
  const { listAdapters, getAdapter } = require(path.join(ROOT, 'packages/adapters'));
  const sample = '## src\n### src/a.js\n```\nfunction a()\n```\n';
  const checked = [];
  for (const name of listAdapters()) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ownout-'));
    try {
      const adapter = getAdapter(name);
      const out = adapter.outputPath(dir);
      if (path.relative(dir, out).startsWith('..')) continue; // willow: no file
      fs.mkdirSync(path.dirname(out), { recursive: true });
      if (typeof adapter.write === 'function') adapter.write(sample, dir, { version: '8.70.0' });
      else fs.writeFileSync(out, adapter.format(sample, { version: '8.70.0' }));
      const rel = path.relative(dir, out).split(path.sep).join('/');
      const read = (p) => fs.readFileSync(path.join(dir, p), 'utf8');
      assert.strictEqual(isSigmapOutput(rel, read), true,
        `${name}: ${rel} is written by SigMap but would count as a changed file`);
      if (name === 'codex') { // `sigmap skills` injects its block above the marker of AGENTS.md
        const { injectSkillsBlock, renderAgentsBlock } = require(path.join(ROOT, 'src/skills/skills'));
        fs.writeFileSync(out, injectSkillsBlock(read(rel), renderAgentsBlock('8.70.0')));
        assert.ok(/sigmap-skills:start/.test(read(rel)), 'the skills block was not injected');
        assert.strictEqual(isSigmapOutput(rel, read), true, 'AGENTS.md with the injected skills block');
      }
      checked.push(name);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  }
  assert.ok(checked.length >= 7, `expected every file adapter checked, got ${checked.join(',')}`);
});

test('own outputs: llms.txt and llm-full.txt are recognised, the hand-filled llm.txt is not', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ownout-'));
  try {
    const ctx = { projectName: 'p', fileEntries: [] };
    const llms = require(path.join(ROOT, 'src/format/llms-txt')).format(ctx, dir, [], '8.70.0');
    const full = require(path.join(ROOT, 'packages/adapters/llm-full')).format(ctx, { version: '8.70.0' });
    const llm = require(path.join(ROOT, 'src/format/llm-txt')).format(ctx, dir, '8.70.0');
    assert.strictEqual(isSigmapOutput('llms.txt', () => llms), true);
    assert.strictEqual(isSigmapOutput('llm-full.txt', () => full), true);
    assert.strictEqual(isSigmapOutput('llm.txt', () => llm), false);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

// ── CLI (real git repo) ─────────────────────────────────────────────────────
function withGitRepo(fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'reviewpr-'));
  const g = (args) => execFileSync('git', args, { cwd: dir, stdio: 'ignore' });
  try {
    g(['init', '-q']);
    g(['config', 'user.email', 't@t.t']);
    g(['config', 'user.name', 'T']);
    g(['commit', '--allow-empty', '-q', '-m', 'base']);
    fn(dir, g);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test('CLI: review-pr --staged flags a sensitive file (exit 1)', () => {
  withGitRepo((dir, g) => {
    fs.writeFileSync(path.join(dir, '.env'), 'SECRET=1\n');
    g(['add', '.env']);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(res.status, 1, res.stdout + res.stderr);
    assert.ok(/sensitive path/.test(res.stdout), res.stdout);
  });
});

test('CLI: review-pr --staged flags a hardcoded secret via content scan (exit 1)', () => {
  withGitRepo((dir, g) => {
    fs.mkdirSync(path.join(dir, 'src'));
    // innocently-named file, no test needed — the secret is the finding
    fs.writeFileSync(path.join(dir, 'src', 'config.js'), 'module.exports = { key: "AKIAABCDEFGHIJKLMNOP" };\n');
    fs.writeFileSync(path.join(dir, 'src', 'config.test.js'), 'require("./config");\n');
    g(['add', '-A']);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(res.status, 1, res.stdout + res.stderr);
    assert.ok(/secret detected/.test(res.stdout), res.stdout);
  });
});
test('CLI: review-pr --staged clean (source + test) exits 0', () => {
  withGitRepo((dir, g) => {
    fs.mkdirSync(path.join(dir, 'src'));
    fs.writeFileSync(path.join(dir, 'src', 'foo.js'), 'module.exports = 1;\n');
    fs.writeFileSync(path.join(dir, 'src', 'foo.test.js'), 'require("./foo");\n');
    g(['add', '-A']);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(res.status, 0, res.stdout + res.stderr);
    assert.ok(/no findings/.test(res.stdout));
  });
});
// The defect as a user met it (#918): generate, stage the real change together
// with what SigMap wrote, review. The same four real dirs passed without the
// generated files and failed with them.
function withGeneratedRepo(fn) {
  withGitRepo((dir, g) => {
    for (const d of ['src', 'lib', 'app', 'test']) fs.mkdirSync(path.join(dir, d));
    fs.writeFileSync(path.join(dir, 'gen-context.config.json'), JSON.stringify({ srcDirs: ['src', 'lib', 'app'] }));
    for (const [d, n] of [['src', 'a'], ['lib', 'b'], ['app', 'c']]) {
      fs.writeFileSync(path.join(dir, d, `${n}.js`), `function ${n}() { return 1; }\nmodule.exports = { ${n} };\n`);
      fs.writeFileSync(path.join(dir, 'test', `${n}.test.js`), `require("../${d}/${n}");\n`);
    }
    const gen = spawnSync('node', [SCRIPT], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(gen.status, 0, gen.stderr);
    g(['add', '-A']);
    fn(dir, g);
  });
}

test('CLI: review-pr --staged ignores what SigMap generated and says so (exit 0)', () => {
  withGeneratedRepo((dir, g) => {
    const staged = execFileSync('git', ['diff', '--cached', '--name-only'], { cwd: dir, encoding: 'utf8' });
    assert.ok(/^\.context\//m.test(staged) && /^\.github\/copilot-instructions\.md$/m.test(staged),
      `the repro needs SigMap's outputs staged:\n${staged}`);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(res.status, 0, res.stdout + res.stderr);
    assert.ok(/review-pr — 7 file\(s\) changed \(3 source, 3 test\)/.test(res.stdout), res.stdout);
    assert.ok(/SigMap-generated output\(s\) in the diff not reviewed/.test(res.stdout), res.stdout);
    assert.ok(!/scope drift/.test(res.stdout), res.stdout);
  });
});

test('CLI: create --staged stage 4/4 passes on that same diff', () => {
  withGeneratedRepo((dir) => {
    const res = spawnSync('node', [SCRIPT, 'create', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.strictEqual(res.status, 0, res.stdout + res.stderr);
    assert.ok(/4\/4 ✓ review-pr/.test(res.stdout), res.stdout);
  });
});

test('CLI: review-pr --json carries the ignored list and count', () => {
  withGeneratedRepo((dir) => {
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged', '--json'], { cwd: dir, encoding: 'utf8' });
    const data = JSON.parse(res.stdout.trim().split('\n').pop());
    assert.ok(data.ignored.includes('.github/copilot-instructions.md'), JSON.stringify(data.ignored));
    assert.ok(data.ignored.every((p) => !p.startsWith('src/')), 'a real source file was ignored');
    assert.strictEqual(data.summary.generatedIgnored, data.ignored.length);
  });
});

test('CLI: review-pr --markdown lists no generated output as a changed file', () => {
  withGeneratedRepo((dir) => {
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--markdown', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.ok(!/#### `\.context\//.test(res.stdout), res.stdout);
    assert.ok(!/risk: source/.test(res.stdout.split('\n').filter((l) => l.includes('.context/')).join('\n')), res.stdout);
    assert.ok(/#### `src\/a\.js`/.test(res.stdout), 'the real change must be listed');
    assert.ok(/SigMap-generated output\(s\) in the diff are not reviewed/.test(res.stdout), res.stdout);
  });
});

test('CLI: review-pr --json emits the result', () => {
  withGitRepo((dir, g) => {
    fs.writeFileSync(path.join(dir, 'package.json'), '{"name":"x"}\n');
    g(['add', '-A']);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--staged', '--json'], { cwd: dir, encoding: 'utf8' });
    const data = JSON.parse(res.stdout.trim().split('\n').pop());
    assert.ok(data.summary);
    assert.ok(Array.isArray(data.findings));
  });
});

// ── PR Evidence Report (G3) ─────────────────────────────────────────────────

/** Temp project with source files for signatures + blast radius. */
function withSrcProject(fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'prev-'));
  try {
    fs.mkdirSync(path.join(dir, 'src'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'gen-context.config.json'), JSON.stringify({ srcDirs: ['src'] }));
    fs.writeFileSync(path.join(dir, 'src', 'auth.js'), 'function login(u, p) { return true; }\nmodule.exports = { login };\n');
    fs.writeFileSync(path.join(dir, 'src', 'consumer.js'), 'const { login } = require("./auth");\nmodule.exports = () => login("a", "b");\n');
    fn(dir);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

test('buildPrEvidence returns per-file structure + review', () => {
  withSrcProject((dir) => {
    const ev = buildPrEvidence([{ path: 'src/auth.js', status: 'M' }], dir, { scope: 'vs main' });
    const a = ev.files.find((f) => f.path === 'src/auth.js');
    assert.ok(a, 'auth.js entry missing');
    assert.strictEqual(a.riskLabel, 'auth');
    assert.ok(a.signatures.length >= 1, 'expected extracted signatures');
    assert.ok(a.blast && a.blast.total >= 1, 'expected blast radius (consumer imports auth)');
    assert.ok(ev.review && ev.review.summary, 'expected review summary');
    assert.strictEqual(ev.scope, 'vs main');
  });
});

test('formatPrEvidenceMarkdown is branded, deterministic, timestamp-free', () => {
  withSrcProject((dir) => {
    const md1 = formatPrEvidenceMarkdown(buildPrEvidence([{ path: 'src/auth.js', status: 'M' }], dir, { scope: 'vs main' }));
    const md2 = formatPrEvidenceMarkdown(buildPrEvidence([{ path: 'src/auth.js', status: 'M' }], dir, { scope: 'vs main' }));
    assert.strictEqual(md1, md2, 'report is not byte-stable');
    assert.ok(/^## 🔍 PR Evidence Report/.test(md1), 'missing branded header');
    assert.ok(/Blast radius:/.test(md1), 'missing blast radius');
    assert.ok(!/\d{4}-\d\d-\d\dT/.test(md1), 'report contains a wall-clock timestamp');
  });
});

test('CLI: review-pr --markdown emits the PR Evidence Report', () => {
  withGitRepo((dir, g) => {
    fs.mkdirSync(path.join(dir, 'src'));
    fs.writeFileSync(path.join(dir, 'src', 'auth.js'), 'function login(u, p) { return true; }\nmodule.exports = { login };\n');
    g(['add', '-A']);
    const res = spawnSync('node', [SCRIPT, 'review-pr', '--markdown', '--staged'], { cwd: dir, encoding: 'utf8' });
    assert.ok(/## 🔍 PR Evidence Report/.test(res.stdout), res.stdout + res.stderr);
    assert.ok(/`src\/auth\.js`/.test(res.stdout), 'changed file not in report');
    assert.strictEqual(res.status, 1, 'auth.js with no test → finding → exit 1');
  });
});

console.log(`\nreview-pr: ${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
